Support getting methods using metaclasses
tox-dev/sphinx-autodoc-typehints pull request #157
Opened 2020-10-23 12:47 UTC by flying-sheep

If a metaclass has a `__getattr__` method, `__dict__` won’t cut it.

2020-10-24 06:33 UTC, agronholm commented
The test suite fails, plus you have not added any tests of your own. Fix those problems and I will review this.

2020-10-24 23:53 UTC, flying-sheep commented
Hmm, seems like I can’t:

Both static methods and normal methods return `types.FunctionType` instances on `getattr` (class methods return `types.MethodType` objects aka bound methods.)

We could use `object.getattribute(outer, method_name)`, but that one probably just uses `__dict__` internally…

2021-12-31 13:15 UTC, gaborbernat commented
@flying-sheep  I've rebased on main, can you please fix the CI, thanks!

2022-01-03 09:57 UTC, flying-sheep commented
You didn’t!

2022-01-03 11:10 UTC, gaborbernat commented
I did but then further changes were made to main that made it out of date.

2022-01-04 11:49 UTC, flying-sheep commented
Interesting that such a trivial change can have conflicts at all. I just remade it.

2022-01-04 12:08 UTC, gaborbernat requested changes
Can we have a test and a changelog for this, please?

2022-01-07 09:34 UTC, gaborbernat commented
@flying-sheep can you please force push back 9ace51eade7dda1e9b98b6266b4316bf6cc4b7be, I by mistake overwritten this branch. Thanks :pray:

2022-01-08 10:16 UTC, gaborbernat commented
On a deeper look, I'm actually not sure how this can happen. The method must already be manifested because otherwise it would not be passed in. I'm closing until we can come up with a case that replicates it :thinking:

2022-01-08 10:16 UTC, closed without merging