Add defaults
tox-dev/sphinx-autodoc-typehints pull request #191
Opened 2022-01-04 09:42 UTC by flying-sheep

Supersedes #103

In the previous PR, I added them to types, this time I’m adding it to the string. I think both have arguments pro and contra. Should it be configurable?

2022-01-04 09:44 UTC, gaborbernat commented
I'd like to have it by default off. Otherwise, I'm happy to also allow it to be configurable where it's added.

2022-01-04 11:28 UTC, flying-sheep commented
OK, I need help, I have no idea what’s going on with those `"`s and `*`s.

2022-01-04 23:00 UTC, gaborbernat commented
> OK, I need help, I have no idea what’s going on with those `"`s and `*`s.
> 
> Why does only my test case fail on Python 3.9 even though I copied the setup from `test_sphinx_output_future_annotations`?

That's half the work in this project, to figure out the differences between Python versions and make it work everywhere. I'll have a look at some point, but no idea when I'll have time for this.

2022-01-05 09:08 UTC, flying-sheep commented
Ugh, I figured it out. This will bite you in the future! So even on 3.9, a simple type like `int` gets compiled to

- `*int*` if the file *contains* new-style union syntax, and
- `"int"` otherwise.

It’s *not* about `from __future__ import annotations`, it’s about actually using the syntax! So:

```py
from __future__ import annotations

def function(x: bool) -> str | int: ...
```

gets compiled to `*`

```
...
Parameters:
   * **x** (*bool*) -- foo
```

And when you don‘t use `|` syntax:

```py
from __future__ import annotations

def function(x: bool) -> str: ...
```

gets compiled to `"`

```
...
Parameters:
   * **x** ("bool") -- foo
```

2022-01-05 09:19 UTC, gaborbernat commented
> Ugh, I figured it out. This will bite you in the future, I hope you find a way to make it less flaky.
> 
> I filed #194 to explore this. But this PR is now ready!

Sorry, I'm not open to a fallback issue and working around the test. We should figure out here and now why this is the case and avoid it.

2022-01-05 09:25 UTC, flying-sheep commented
I’m avoiding it by not using that syntax, in the same way your main test does. This PR is completely independent of this problem now, I just happened to run into it while developing this PR.

2022-01-05 09:51 UTC, gaborbernat requested changes

2022-01-05 09:51 UTC, gaborbernat commented on src/sphinx_autodoc_typehints/__init__.py
> +def builder_ready(app: Sphinx):
Let's type-hint the return value to if you're going to type annotate it.

2022-01-05 09:51 UTC, gaborbernat commented on src/sphinx_autodoc_typehints/__init__.py
> +        raise ValueError(f"typehints_defaults needs to be one of {valid!r}, not {app.config.typehints_defaults!r}")
test for this please

2022-01-05 09:51 UTC, gaborbernat commented on src/sphinx_autodoc_typehints/__init__.py
> +        return None
If this is the case the method will never be called so I don't think we need this

2022-01-05 10:54 UTC, merged