Added options to retain original typehints in signatures
tox-dev/sphinx-autodoc-typehints pull request #278
Opened 2023-01-04 09:38 UTC by BhavyeMathur

I was using this library and noticed that there was no existing way to retain the typehints automatically generated by autodoc in function/class/method signatures. I quite liked the way that return types are annotated with the -> in signatures and wanted to preserve those while using autodoc-typehints.

This pull request adds 2 simple options that **do not alter the behaviour of anyone already using typehints**:

1. `typehints_use_signature` (`False` by default)
2. `typehints_use_signature_return` (`False` by default)

By setting these, the `sph_signature.replace()` commands in `process_signature()` can be altered

With default options:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/67759015/210525359-4398bbf4-fee7-48ab-bd5c-c9b360ca6081.png">

With the new options set to `True`:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/67759015/210525788-ed48433d-df97-42f5-8c60-5899c65b62a9.png">

2023-01-04 15:34 UTC, gaborbernat requested changes
Tests, please!

2023-01-05 03:52 UTC, BhavyeMathur commented
Hey! So I'm new to pull requests and to sphinx. Any particular tests you're looking for?

2023-01-05 15:59 UTC, gaborbernat commented
Test for all features you've added.

2023-01-05 17:13 UTC, gaborbernat requested changes

2023-01-05 17:13 UTC, gaborbernat commented on .gitignore
> +.idea*
Remove this, IDE ignore should be in your global gitignore not per project.

2023-01-05 17:21 UTC, gaborbernat approved these changes

2023-01-05 17:25 UTC, merged